name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - "releases/*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run prepare
      - uses: ./
        with:
          direnvVersion: 2.32.3
      - run: |
          which direnv
          direnv --version | grep -F 2.32.3

  test-default-option:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run prepare
      - uses: ./
      - run: |
          which direnv
          direnv --version | grep -F 2.32.1
